export const ErrorCodes = {
    EMAIL_NOT_UNIQUE: 'EMAIL_NOT_UNIQUE',
    AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED',
    NOT_UNIQUE: 'NOT_UNIQUE',
    MOVIE_EXISTS: 'MOVIE_EXISTS',
    FORMAT_ERROR: 'FORMAT_ERROR',
    REQUIRED: 'REQUIRED',
    MOVIE_NOT_FOUND: 'MOVIE_NOT_FOUND',


    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  } as const;
  
  export type ErrorCode = keyof typeof ErrorCodes;